---
title: "Landscape element response plots"
author: "Trond Simensen"
date: "03 11 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
rm(list=ls())
#setwd("C:/Users/trosim/Documents/PhD/Subproject_2/Landscape_Analysis_Git_Hub/NiN_Landscape_Analysis")
#getwd()

# Loading libraries
library (readxl)#for reading in data
library(vegan)  #vegan 2.4.0
library(graphics)  #for å kunne identifisere punkter på ordinasjonsdiagram
library(knitr)
#library(formattable)
library(knitr)
library(kableExtra)
library(goeveg)
library(vegan)
```

```{r, include=FALSE}
#Importerer data(matriser)
#Aktuelle datamatriser er: 

spreadsheet_filename  <-  "XSpFreq.xlsx" # Setting the filename to the spreadsheet containg data

# Reading in data, specifying which columns to read with the command 'range'
sheetname  <-  "Dta" # Setting the name of the sheet within the spreadsheet containing data

sp <- read_excel(spreadsheet_filename, sheet = sheetname, range = cell_cols("C:GF"), col_names = TRUE) #analysis variables,

sp <- sp[c(1:100), ]
attach(sp)

y<-sp
```

```{r, include=FALSE}

### SPECIES LEVEL

gnmds1_sp <- read.csv("gnmds1_sp.csv")
gnmds1_sp <- gnmds1_sp [ , 2]

palette(c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", 
                    "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99", "#b15928"))
#rgb( ramp(seq(0, 1, length = 5)), max = 255)

specresponse3 <- function(species, var, main, xlab, model = "auto", method = "env", axis = 1, points = FALSE, bw = FALSE) {
  
  if(!is.data.frame(species)) {
    
    if(missing(main)) {
      main <- deparse(substitute(species))
    }
    
    specnames <- deparse(substitute(species))
    species <- data.frame(species)
    ismat <- F
    
  } else {
    if(missing(main)) {
      main <- " "
    }
    specnames <- names(species)
    ismat <- T
  }
  
  species <- decostand(species, method = "pa")
  
  if(length(species) >= 1) {
    
    ls <- length(species)
    
    if(method == "env") {
      
      if(missing(xlab)) {
        xlab <- deparse(substitute(var))
      }
    } else if(method == "ord") {
      
      # Extract site scores from ordination
      var <- as.numeric(scores(var, display="sites", choices=axis))
      
      # X-axis labeling
      if(missing(xlab)) {
        xlab <- paste("Axis", axis, "sample scores")
      }
    } else {
      stop("Method unknown.")
    }
    
    plot(var, species[,1], main = " ", type="n", frame = FALSE, 
         xlab = " ", ylab=" ", cex.axis = 0.7, cex.lab = 0.7, cex.main=0.7, xlim=c(-0.8,1), ylim = c(0,1))
    
    for(i in 1:ls) {
      
      if(length(species[species[,i]>0,i]) <= 5) {
        # tried warning instead of print
        warning(paste("Only", length(species[species[,i]>0,i]), "occurrences of", names(species)[i], "."))
      }
      
      if(model == "unimodal") {
        
        specresponse <- suppressWarnings(glm(species[,i] ~ poly(var, 2),
                                             family="binomial"))
        
      } else if (model == "linear") {
        
        specresponse <- suppressWarnings(glm(species[,i] ~ var,
                                             family="binomial"))
        
      } else if (model == "bimodal") {
        
        specresponse <- suppressWarnings(glm(species[,i] ~ poly(var, 4),
                                             family="binomial"))
        
      }
      else if (model == "auto") {
        
        glm.1 <- suppressWarnings(glm(species[,i] ~ poly(var, 1), family="binomial"))
        glm.2 <- suppressWarnings(glm(species[,i] ~ poly(var, 2), family="binomial"))
        glm.3 <- suppressWarnings(glm(species[,i] ~ poly(var, 3), family="binomial"))
        glm.AIC <- c(extractAIC (glm.1)[2], extractAIC (glm.2)[2],
                     extractAIC (glm.3)[2])
        
        switch(c(1,2,3)[glm.AIC==min(glm.AIC)],
               {specresponse <- glm.1; deg<-1},
               {specresponse <- glm.2; deg<-2},
               {specresponse <- glm.3; deg<-3})
        

      } else if (model == "gam") {
        
        gam.list <- list()
        gam.AIC <- 0
        
        for(n in 1:4) {
          gam.list[[paste("gam", n, sep=".")]] <- mgcv::gam(species[,i] ~ s(var, k = n+2), family='binomial')
          gam.AIC[n] <- extractAIC(gam.list[[n]])[2]
        }
        
        switch(c(1,2,3,4)[gam.AIC==min(gam.AIC)],
               {specresponse <- gam.list[[1]]; deg<-3},
               {specresponse <- gam.list[[2]]; deg<-4},
               {specresponse <- gam.list[[3]]; deg<-5},
               {specresponse <- gam.list[[4]]; deg<-6})
        
      } else {
        stop("Model unknown.")
      }
      
      xneu <- seq(min(var), max(var), len = 101)
      preds <- predict(specresponse, newdata = data.frame(var = xneu),
                       type="response")
      
      if(bw == T) {
        if(points == TRUE) {
          if(i > 1) {
            species[,i][species[,i]==1] <- species[,i][species[,i]==1] - 0.02*(i-1)
            species[,i][species[,i]==0] <- species[,i][species[,i]==0] + 0.02*(i-1)
          }
          
          col <- col2rgb(i)
          points(var, species[,i], pch = i,
                 col = rgb( ramp(seq(0, 1, length = 5)), maxColorValue = 255))
        }
        
        lines(preds ~ xneu, lty=i)
      } else {
        
        if(points == TRUE) {
          if(i > 1) {
            species[,i][species[,i]==1] <- species[,i][species[,i]==1] - 0.02*(i-1)
            species[,i][species[,i]==0] <- species[,i][species[,i]==0] + 0.02*(i-1)
          }
          
          col <- col2rgb(i)
          points(var, species[,i],
                 col = rgb( ramp(seq(0, 1, length = 5)), maxColorValue = 255),
                 pch = 16)
        }
        
        lines(preds ~ xneu, lty = i, lwd= 2, col = i)
      }
    }
    
    if(ismat == T) {
      
      if(bw == T){
        if(points == TRUE) {
          legend(0.70, 0.75,legend= "names(species)", "b", lty=1:ls, lwd = 2, pch=1:ls,
                 bty = "n", cex = 0.85)
        } else {
          legend(0.70, 0.75, legend= "names(spees)", lty=1:ls, lwd = 2, pch=1:ls,
                 bty = "n", cex = 0.85)
        }
      } else {
        legend(1.05, 1, legend= c("Picea abies", "Pinus sylvestris", "Sorbus aucuparia", "Calluna vulgaris", "Anemone nemorosa", "Linnaea borealis", "Maianthemum bifolium", "Dicranum polysetum", "Hylocomium splendens"), title="Species", title.adj = 0.1, lty=1:ls, text.font=3, lwd = 2, col=1:ls, 
               bty = "n", cex = 0.6)
      }
    }
    
  }  else {
    stop("No species in matrix.")
  }
}
```


```{r, include=FALSE}

### LANDSCAPE LEVEL

av_ia <- read.csv("av_ia.csv", header = TRUE, sep = ",")
av_ia <- av_ia[ ,c(2:67)]
akse1_ia <- read.csv("akse1_ia.csv")
akse1_ia <- akse1_ia [,2]

palette(c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99", "#b15928"))


specresponse2 <- function(species, var, main, xlab, model = "auto", method = "env", axis = 1, points = FALSE, bw = FALSE) {
  
  if(!is.data.frame(species)) {
    
    if(missing(main)) {
      main <- deparse(substitute(species))
    }
    
    specnames <- deparse(substitute(species))
    species <- data.frame(species)
    ismat <- F
    
  } else {
    if(missing(main)) {
      main <- " "
    }
    specnames <- names(species)
    ismat <- T
  }
  
  species <- decostand(species, method = "pa")
  
  if(length(species) >= 1) {
    
    ls <- length(species)
    
    if(method == "env") {
      
      if(missing(xlab)) {
        xlab <- deparse(substitute(var))
      }
    } else if(method == "ord") {
      
      # Extract site scores from ordination
      var <- as.numeric(scores(var, display="sites", choices=axis))
      
      # X-axis labeling
      if(missing(xlab)) {
        xlab <- paste("Axis", axis, "sample scores")
      }
    } else {
      stop("Method unknown.")
    }
    
    plot(var, species[,1], main = " ", type="n", frame = FALSE, 
         xlab = " ", ylab=" ", cex.axis = 0.7, cex.lab = 0.7, cex.main=0.7, xlim=c(-0.8,1), ylim = c(0,1))
    
    for(i in 1:ls) {
      
      if(length(species[species[,i]>0,i]) <= 5) {
        # tried warning instead of print
        warning(paste("Only", length(species[species[,i]>0,i]), "occurrences of", names(species)[i], "."))
      }
      
      if(model == "unimodal") {
        
        specresponse <- suppressWarnings(glm(species[,i] ~ poly(var, 2),
                                             family="binomial"))
        
      } else if (model == "linear") {
        
        specresponse <- suppressWarnings(glm(species[,i] ~ var,
                                             family="binomial"))
        
      } else if (model == "bimodal") {
        
        specresponse <- suppressWarnings(glm(species[,i] ~ poly(var, 4),
                                             family="binomial"))
        
      }
      else if (model == "auto") {
        
        glm.1 <- suppressWarnings(glm(species[,i] ~ poly(var, 1), family="binomial"))
        glm.2 <- suppressWarnings(glm(species[,i] ~ poly(var, 2), family="binomial"))
        glm.3 <- suppressWarnings(glm(species[,i] ~ poly(var, 3), family="binomial"))
        glm.AIC <- c(extractAIC (glm.1)[2], extractAIC (glm.2)[2],
                     extractAIC (glm.3)[2])
        
        switch(c(1,2,3)[glm.AIC==min(glm.AIC)],
               {specresponse <- glm.1; deg<-1},
               {specresponse <- glm.2; deg<-2},
               {specresponse <- glm.3; deg<-3})
        
        
      } else if (model == "gam") {
        
        gam.list <- list()
        gam.AIC <- 0
        
        for(n in 1:4) {
          gam.list[[paste("gam", n, sep=".")]] <- mgcv::gam(species[,i] ~ s(var, k = n+2), family='binomial')
          gam.AIC[n] <- extractAIC(gam.list[[n]])[2]
        }
        
        switch(c(1,2,3,4)[gam.AIC==min(gam.AIC)],
               {specresponse <- gam.list[[1]]; deg<-3},
               {specresponse <- gam.list[[2]]; deg<-4},
               {specresponse <- gam.list[[3]]; deg<-5},
               {specresponse <- gam.list[[4]]; deg<-6})
        
      } else {
        stop("Model unknown.")
      }
      
      xneu <- seq(min(var), max(var), len = 101)
      preds <- predict(specresponse, newdata = data.frame(var = xneu),
                       type="response")
      
      if(bw == T) {
        if(points == TRUE) {
          if(i > 1) {
            species[,i][species[,i]==1] <- species[,i][species[,i]==1] - 0.02*(i-1)
            species[,i][species[,i]==0] <- species[,i][species[,i]==0] + 0.02*(i-1)
          }
          
          col <- col2rgb(i)
          points(var, species[,i], pch = i,
                 col = rgb( ramp(seq(0, 1, length = 5)), max = 255))
        }
        
        lines(preds ~ xneu, lty=i)
      } else {
        
        if(points == TRUE) {
          if(i > 1) {
            species[,i][species[,i]==1] <- species[,i][species[,i]==1] - 0.02*(i-1)
            species[,i][species[,i]==0] <- species[,i][species[,i]==0] + 0.02*(i-1)
          }
          
          col <- col2rgb(i)
          points(var, species[,i],
                 col = rgb( ramp(seq(0, 1, length = 5)), max = 255),
                 pch = 16)
        }
        
        lines(preds ~ xneu, lty = i, lwd= 2, col = i)
      }
    }
    
    if(ismat == T) {
      
      if(bw == T){
        if(points == TRUE) {
          legend(0.70, 0.75,legend= "names(species)", "b", lty=1:ls, lwd = 2, pch=1:ls,
                 bty = "n", cex = 0.85)
        } else {
          legend(0.70, 0.75, legend= "names(spees)", lty=1:ls, lwd = 2, pch=1:ls,
                 bty = "n", cex = 0.85)
        }
      } else {
        legend(1.05, 1, legend= c("Large river", "Landslide soil", "Mire", "Glacier", "Lacustrine deposits", "Rugged terrain", "Boral heathlands" , "Cultivated land" , "Surface cultivated land"), title="Landscape elements", title.adj = 0.1, lty=1:ls, lwd = 2, col=1:ls, 
               bty = "n", cex = 0.6)
      }
    }
    
  }  else {
    stop("No species in matrix.")
  }
}
```


```{r, echo=FALSE}
species_subset <- cbind (gnmds1_sp, y)
species_subset <- subset(species_subset, gnmds1_sp > -0.8324644 )
species_subset <- subset(species_subset, gnmds1_sp < 1 )


y2 <- species_subset[ , c(2:187)]
sp_gnmds1 <- species_subset[ , 1]

par(mfrow=c(2,1), mar=c(3,4,1,12), xpd=TRUE)
specresponse3 (y2[ ,c(4,5,9, 11,18,35,38, 82, 91)], main = "Ecosystem level", sp_gnmds1, xlab = "GNMDS 1 (Boreal forest)")
title(xlab="GNMDS 1 Boreal forest", line=2, cex.lab=0.7)
title(ylab="Probability of occurence", line=2, cex.lab=0.7)
title(main = "(a)", cex.main=0.8, adj = 0.02)
specresponse2 (av_ia[ ,c(6, 8, 17, 18, 21, 34, 46, 65, 66)], main = "Landscape level", akse1_ia, model = "gam", xlab = "GNMDS 1 (Inland hills and mountains)")
title(ylab="Probability of occurence", line=2, cex.lab=0.7)
title(xlab="GNMDS 1 Inland hills and mountains", line=2, cex.lab=0.7)
title(main = "(b)", cex.main=0.8, adj = 0.02)
```
```{r, include=FALSE}
names(av_ia[ ,c(6, 8, 17, 18, 21, 34, 46, 65, 66)])
#names(y2[ ,c(16:20)])
```

